#cloud-config
users:
  - name: falko
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0FACdqVvsOPOo5fGbivexD8jRa6KoJarpnqtfHdbHrzpG/HC2oC/oUTxquOSksqOVevsOoHSFlmo2MPN1ZH44Qz9BDzJMd75+ldg2nuhWNPTfrOjF/CKvT3yIE8p1pJv3GLiNE+Y0dwqEGX0ikIn3lTESE8onoNcGVbLaS77yZjc5CaSOdOrxt3z8vUaE48jaXYQ3lAc46fwv6qoqLN1IHJlfCYIB1mQHqYN7ucgLoVp2XV0ytogxzrZflyw+VIt859Pg80+08nqSJXUA7lFgND6pRT2MbOFpJJirLsbOzXyBWqlFKZpay4TlcPyms6DAuaEUoU5ulymQXVT2pOwu+MOweqrZ77kSajRpOR4hsPuTKOx5EqnqoeanMU/ZhMaG65d6v0c4YPETlaIW0WTRsP6LQhJXQH8sh6vqaQnJDzvxi/PXKEBJJ+09gHqAgmKckk852rSpOqoqhin6XNknX3nk7oWIjwrJz936U//Dt6hN/QbVeKM65kZGCho7Gi0= falko@foo
repo_update: true
repo_upgrade: all
package_update: true
package_upgrade: true
packages:
- vim
- git
- tmux
write_files:
- content: |
    # /bin/bash
    #IP=$( dig +short myip.opendns.com @resolver1.opendns.com )
    IP=$(https://api.ipify.org/?format=text)
    #IP=$( curl https://ip4.seeip.org )
    echo $IP
    curl -v -u ${dyndnsuser}:${dyndnspass} "${dyndnsurl}?subdomain=${hostname}&domain=${domain}&address=$IP"
    exit 0
  path: /root/updatedns.sh
  permissions: "0755"
runcmd:
  - apt-get update -y && apt-get -y dist-upgrade && apt-get -y autoremove
  # twice, sometimes it doesn't work
  - sleep 5
  - apt-get install -y curl git wget apt-file inetsim
  - apt-file update
  - /root/updatedns.sh
  - echo "service_bind_address $( curl -s https://api.ipify.org/?format=text )" >> /etc/inetsim/inetsim.conf
  - echo "dns_default_ip $( curl -s https://api.ipify.org/?format=text )" >> /etc/inetsim/inetsim.conf
  - systemctl --now enable inetsim
  - systemctl restart inetsim
