#cloud-config
users:
  - name: falko
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0FACdqVvsOPOo5fGbivexD8jRa6KoJarpnqtfHdbHrzpG/HC2oC/oUTxquOSksqOVevsOoHSFlmo2MPN1ZH44Qz9BDzJMd75+ldg2nuhWNPTfrOjF/CKvT3yIE8p1pJv3GLiNE+Y0dwqEGX0ikIn3lTESE8onoNcGVbLaS77yZjc5CaSOdOrxt3z8vUaE48jaXYQ3lAc46fwv6qoqLN1IHJlfCYIB1mQHqYN7ucgLoVp2XV0ytogxzrZflyw+VIt859Pg80+08nqSJXUA7lFgND6pRT2MbOFpJJirLsbOzXyBWqlFKZpay4TlcPyms6DAuaEUoU5ulymQXVT2pOwu+MOweqrZ77kSajRpOR4hsPuTKOx5EqnqoeanMU/ZhMaG65d6v0c4YPETlaIW0WTRsP6LQhJXQH8sh6vqaQnJDzvxi/PXKEBJJ+09gHqAgmKckk852rSpOqoqhin6XNknX3nk7oWIjwrJz936U//Dt6hN/QbVeKM65kZGCho7Gi0= falko@foo
repo_update: true
repo_upgrade: all
package_update: true
package_upgrade: true
packages:
- vim
- git
- tmux
write_files:
- content: |
    # /bin/bash
    #IP=$( dig +short myip.opendns.com @resolver1.opendns.com )
    IP=$(https://api.ipify.org/?format=text)
    #IP=$( curl https://ip4.seeip.org )
    echo $IP
    curl -v -u ${dyndnsuser}:${dyndnspass} "${dyndnsurl}?subdomain=${hostname}&domain=${domain}&address=$IP"
    exit 0
  path: /root/updatedns.sh
  permissions: "0755"
runcmd:
  - echo "185.12.64.3 mirror.hetzner.com" >> /etc/hosts
  - echo "2a01:4ff:ff00::3:3  mirror.hetzner.com" >> /etc/hosts
  # updates holen und fehlende Pakete installieren
  - apt-get update -y && apt-get -y dist-upgrade && apt-get -y autoremove
  # twice, sometimes it doesn't work
  - sleep 5
  - apt install -y aria2 binwalk capstone-tool edb-debugger file exiftool gdb git hexedit libboost-dev libcapstone-dev libpython3-dev libz3-dev llvm locate ltrace nasm nmap python3-ptrace sed wget z3
  # - apt install radare2
  - /root/updatedns.sh
  - nameserver umstellen
  #- /usr/bin/sed -i "/\[Resolve\]/a DNS=${dns4} ${dns6}" /etc/systemd/resolved.conf
  - systemctl stop systemd-resolved.service
  - systemctl disable systemd-resolved.service
  - rm /etc/resolv.conf
  - echo "nameserver ${dns4}" > /etc/resolv.conf
  - echo "nameserver ${dns6}" >> /etc/resolv.conf
  - echo "dns ${dns4} ${dns6}" > /root/ready 
